# -*- coding: utf-8 -*-
"""sweetviz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18oexN-wp0cXOYlNRijxaVdhKwbMFCTID
"""

!pip install sweetviz

# Importing the libraries 
import pandas as pd
import numpy as np
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns
import sweetviz as sv

# Importing the Boston Housing dataset
from sklearn.datasets import load_boston
boston = load_boston()

# Initializing the dataframe
df = pd.DataFrame(boston.data)

# See head of the dataset
df.head()

my_report = sv.analyze(df)
my_report.show_notebook()

